language: go
install: go get -v github.com/spf13/hugo
script: make clean build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  fqdn: trevorbrindle.com
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: dev
notifications:
  email:
    on_failure: always